[package]
name = "add-daily-tasks"
version = "0.1.0"
authors = ["jp <jpenno123@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"

[dev-dependencies]
pretty_assertions = "1.0.0"